import os
import uuid
import struct
import mimetypes
from typing import Optional
from google import genai
from google.genai import types
from utils.asset_directory_utils import get_exports_directory
from utils.get_env import get_google_api_key_env
from utils.async_iterator import iterator_to_async

def parse_audio_mime_type(mime_type: str) -> dict[str, int | None]:
    """Parses bits per sample and rate from an audio MIME type string."""
    bits_per_sample = 16
    rate = 24000

    parts = mime_type.split(";")
    for param in parts:
        param = param.strip()
        if param.lower().startswith("rate="):
            try:
                rate_str = param.split("=", 1)[1]
                rate = int(rate_str)
            except (ValueError, IndexError):
                pass
        elif param.startswith("audio/L"):
            try:
                bits_per_sample = int(param.split("L", 1)[1])
            except (ValueError, IndexError):
                pass

    return {"bits_per_sample": bits_per_sample, "rate": rate}

def convert_to_wav(audio_data: bytes, mime_type: str) -> bytes:
    """Generates a WAV file header for the given audio data and parameters."""
    parameters = parse_audio_mime_type(mime_type)
    bits_per_sample = parameters["bits_per_sample"]
    sample_rate = parameters["rate"]
    num_channels = 1
    data_size = len(audio_data)
    bytes_per_sample = bits_per_sample // 8
    block_align = num_channels * bytes_per_sample
    byte_rate = sample_rate * block_align
    chunk_size = 36 + data_size

    header = struct.pack(
        "<4sI4s4sIHHIIHH4sI",
        b"RIFF",
        chunk_size,
        b"WAVE",
        b"fmt ",
        16,
        1,
        num_channels,
        sample_rate,
        byte_rate,
        block_align,
        bits_per_sample,
        b"data",
        data_size
    )
    return header + audio_data

class GeminiTTSService:
    """Service to generate speech from text using Google Gemini API"""
    
    def __init__(self):
        self.api_key = get_google_api_key_env()
        if not self.api_key:
            print("Warning: GOOGLE_API_KEY not set.")
        self.client = genai.Client(api_key=self.api_key)
        self.audio_dir = os.path.join(get_exports_directory(), "narrations")
        os.makedirs(self.audio_dir, exist_ok=True)
    
    async def generate_speech(
        self,
        text: str,
        language_code: str = "en",
        gender: str = "female",
        source_lang: str = "en"
    ) -> tuple[str, str]:
        """
        Generate speech using Gemini TTS.
        Ignores source_lang as Gemini handles the text directly.
        """
        try:
            # Map gender to voice
            # Available voices: Aoede, Charon, Fenrir, Kore, Puck, Zephyr
            # Assuming:
            # Female: Zephyr, Aoede, Kore
            # Male: Puck, Charon, Fenrir
            voice_name = "Zephyr" if gender.lower() == "female" else "Puck"
            
            model = "gemini-2.5-pro-preview-tts"
            
            contents = [
                types.Content(
                    role="user",
                    parts=[
                        types.Part.from_text(text=text),
                    ],
                ),
            ]
            
            generate_content_config = types.GenerateContentConfig(
                temperature=1,
                response_modalities=["audio"],
                speech_config=types.SpeechConfig(
                    voice_config=types.VoiceConfig(
                        prebuilt_voice_config=types.PrebuiltVoiceConfig(
                            voice_name=voice_name
                        )
                    )
                ),
            )

            audio_data = b""
            mime_type = "audio/wav" # Default

            # Use iterator_to_async to handle the synchronous generator
            async for chunk in iterator_to_async(self.client.models.generate_content_stream)(
                model=model,
                contents=contents,
                config=generate_content_config,
            ):
                if (
                    chunk.candidates is None
                    or not chunk.candidates
                    or chunk.candidates[0].content is None
                    or chunk.candidates[0].content.parts is None
                    or not chunk.candidates[0].content.parts
                ):
                    continue
                
                part = chunk.candidates[0].content.parts[0]
                if part.inline_data and part.inline_data.data:
                    audio_data += part.inline_data.data
                    mime_type = part.inline_data.mime_type

            if not audio_data:
                raise ValueError("No audio content generated by Gemini")

            # Convert to WAV if needed (Gemini usually returns raw PCM or similar wrapped in a container, 
            # but the snippet suggests we might need to add a header if it's raw PCM)
            # The snippet logic:
            # if file_extension is None: file_extension = ".wav"; data_buffer = convert_to_wav(...)
            # It seems Gemini returns raw audio data without header for some mime types?
            # Let's assume we always want to ensure it's a valid WAV.
            
            # If mime_type implies raw PCM (e.g. audio/pcm or similar), we definitely need convert_to_wav.
            # The snippet calls convert_to_wav if extension is None (guessed from mime type).
            # mimetypes.guess_extension("audio/L16;rate=24000") might return None.
            
            ext = mimetypes.guess_extension(mime_type)
            if ext is None or ext == ".wav": # Force WAV conversion/header addition if it looks like raw data or we want wav
                # The snippet logic is a bit specific. Let's follow it.
                # If it's already a wav file (with header), adding another header is bad.
                # But the snippet implies the data returned needs a header constructed.
                # "audio/L16;rate=24000" is raw PCM.
                if "audio/L16" in mime_type or "audio/pcm" in mime_type:
                     audio_data = convert_to_wav(audio_data, mime_type)
            
            return await self._save_audio_file(audio_data, language_code)

        except Exception as e:
            print(f"[GeminiTTS] Error: {e}")
            raise

    async def _save_audio_file(self, audio_bytes: bytes, language_code: str) -> tuple[str, str]:
        """
        Save audio bytes to file
        """
        # Create language-specific subdirectory
        lang_dir = os.path.join(self.audio_dir, language_code)
        os.makedirs(lang_dir, exist_ok=True)
        
        # Generate unique filename
        filename = f"{uuid.uuid4()}.wav"
        file_path = os.path.join(lang_dir, filename)
        
        try:
            with open(file_path, "wb") as f:
                f.write(audio_bytes)
            
            # Generate URL (relative to app_data directory)
            audio_url = f"/app_data/exports/narrations/{language_code}/{filename}"
            
            return file_path, audio_url
            
        except Exception as e:
            print(f"Error saving audio file: {e}")
            raise

    def get_supported_languages(self) -> dict[str, str]:
        """Get supported language codes - Gemini supports many, but we'll list common ones or same as Bhashini for compatibility"""
        return {
            "hi": "Hindi",
            "bn": "Bengali",
            "ta": "Tamil",
            "te": "Telugu",
            "mr": "Marathi",
            "gu": "Gujarati",
            "kn": "Kannada",
            "ml": "Malayalam",
            "pa": "Punjabi",
            "or": "Odia",
            "en": "English",
            "es": "Spanish",
            "fr": "French",
            "de": "German",
            # Add more as needed
        }

# Singleton instance
_gemini_tts_service: Optional[GeminiTTSService] = None

def get_gemini_tts_service() -> GeminiTTSService:
    """Get or create Gemini TTS service instance"""
    global _gemini_tts_service
    if _gemini_tts_service is None:
        _gemini_tts_service = GeminiTTSService()
    return _gemini_tts_service
