import React from "react";
import * as z from "zod";
import { VideoSchema } from "@/presentation-templates/defaultSchemes";
import VideoPlayer from "@/presentation-templates/shared/VideoPlayer";

export const layoutId = "standard-video-slide";
export const layoutName = "Video Slide";
export const layoutDescription =
  "A slide layout designed to showcase a video animation, perfect for demonstrating concepts, processes, or mathematical transformations.";

const videoSlideSchema = z.object({
  title: z.string().min(3).max(40).default("Concept Demonstration").meta({
    description: "Main title of the slide",
  }),
  description: z
    .string()
    .min(20)
    .max(200)
    .default(
      "This video demonstrates the core concept. Watch closely to understand the transformation.",
    )
    .meta({
      description: "Description of the video content",
    }),
  video: VideoSchema.meta({
    description: "The video animation to display",
  }),
});

export const Schema = videoSlideSchema;

export type VideoSlideData = z.infer<typeof videoSlideSchema>;

interface VideoSlideLayoutProps {
  data?: Partial<VideoSlideData>;
}

const VideoSlideLayout: React.FC<VideoSlideLayoutProps> = ({
  data: slideData,
}) => {
  const title = slideData?.title || "Concept Demonstration";
  const description = slideData?.description || "Video description goes here.";
  const videoUrl = slideData?.video?.__video_url__;
  const videoPrompt = slideData?.video?.__video_prompt__;

  return (
    <>
      <div className="h-full w-full bg-white p-8 flex flex-col relative overflow-hidden">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">{title}</h1>
          <p className="text-lg text-gray-600">{description}</p>
        </div>

        {/* Video Container */}
        <div className="flex-grow flex items-center justify-center bg-gray-100 rounded-lg overflow-hidden relative">
          {videoUrl ? (
            <VideoPlayer src={videoUrl} prompt={videoPrompt} />
          ) : (
            <div className="flex flex-col items-center justify-center text-gray-400 p-8 text-center">
              <div className="text-6xl mb-4">🎬</div>
              <p className="text-xl font-semibold">Video Placeholder</p>
              <p className="text-sm mt-2 max-w-md">{videoPrompt || "No video prompt provided"}</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-6 flex justify-between items-center text-sm text-gray-400 border-t pt-4">
          <span>Generated by Medhavi</span>
          <span>{new Date().toLocaleDateString()}</span>
        </div>
      </div>
    </>
  );
};

export default VideoSlideLayout;
